// Generated by scripts/i18n-translate-catalog.mjs from the English landing copy. Machine translation: review before relying on wording.
export default {
  metaTitle: '30Grow : recrutement, profils de travail et gestion des personnes',
  metaDescription: 'Plateforme RH pour recruter, développer et accompagner les personnes. Essayez pendant 30 jours ; les 20 premières entreprises bénéficient de 90 jours gratuits.',
  metaKeywords: 'logiciel RH, recrutement avec profil Ennéagramme, adéquation à l\'équipe, ATS et gestion des personnes, évaluation des Motivateurs, gestion des 1:1, OKR, LMS d\'entreprise, portail collaborateur, application mobile collaborateur, climat social, points d\'intégration, 30Grow, 3035Tech, accès anticipé RH',
  earlyBadge: '30 jours d\'essai · 90 jours pour les 20 premières',
  ui: {
    showAllFeatures: "Voir toutes les fonctionnalités",
    showFewerFeatures: "Afficher moins",
    mainNavigation: 'Navigation principale',
    navJourney: 'Fonctionnement',
    navModules: 'Modules',
    navPricing: 'Tarifs',
    navEnneagram: 'Ennéagramme',
    exploreProduct: 'Découvrir les fonctionnalités',
    heroProof: [
      '30 jours gratuits',
      'Sans carte bancaire',
      '5 collaborateurs minimum',
    ],
    previewAria: 'Aperçu de l\'expérience produit 30Grow',
    liveWorkspace: 'produit réel',
    teamReading: 'Intelligence d\'équipe',
    previewTitle: 'Vue d\'ensemble des personnes et du recrutement',
    updated: 'Mis à jour',
    typeMap: 'Carte des styles de travail',
    nextConversation: 'Prochain échange',
    hypothesis: 'Aligner autonomie et critères de décision.',
    hedging: 'Une hypothèse pour guider l\'échange, jamais un diagnostic.',
    pipeline: 'Pipeline du poste',
    candidates: '7 candidats',
    pipelineStages: [
      'Entretien',
      'Test terminé',
      'Validé',
    ],
    previewCaption: 'Composition illustrative basée sur les écrans et fonctionnalités actuels de 30Grow.',
    humanContextEyebrow: 'La technologie au service de l\'échange',
    humanContextTitle: 'De meilleures décisions commencent par un meilleur échange.',
    humanContextBody: '30Grow organise les signaux, le contexte et les prochaines étapes pour que les RH et les dirigeants arrivent mieux préparés aux échanges qui comptent.',
    humanContextAlt: 'Professionnels RH et dirigeants en discussion dans un bureau contemporain.',
    coverageLabel: 'Une plateforme pour',
    coverageItems: [
      'Recruter',
      'Comprendre',
      'Développer',
      'Engager',
      'Gérer',
    ],
    enneagramLabel: 'L\'Ennéagramme appliqué au travail',
    enneagramTitle: 'Neuf styles. Plus de contexte pour chaque échange.',
    enneagramBody: 'T1–T9 aide à observer des tendances dans le travail, la communication et la prise de décision. Dans 30Grow, ce contexte suit la personne de la sélection au développement, toujours présenté comme une hypothèse.',
    enneagramPoints: [
      'Grille par poste et classement explicable',
      'Compatibilité et composition d\'équipe',
      'Synthèses pour entretiens et 1:1',
      'Aucun rapport clinique ni diagnostic',
    ],
    typesAria: 'Neuf styles de travail de T1 à T9',
    types: [
      {
        name: 'Exigence',
        signal: 'qualité et rigueur',
      },
      {
        name: 'Soutien',
        signal: 'coopération et liens',
      },
      {
        name: 'Résultats',
        signal: 'rythme et accomplissement',
      },
      {
        name: 'Expression',
        signal: 'identité et sens',
      },
      {
        name: 'Analyse',
        signal: 'profondeur et autonomie',
      },
      {
        name: 'Sécurité',
        signal: 'anticipation et confiance',
      },
      {
        name: 'Possibilités',
        signal: 'énergie et exploration',
      },
      {
        name: 'Direction',
        signal: 'force et décision',
      },
      {
        name: 'Harmonie',
        signal: 'médiation et stabilité',
      },
    ],
    modulesNote: 'Chaque entreprise active uniquement les modules dont elle a besoin. La navigation et les permissions suivent ce choix sans supprimer les données existantes.',
  },
  heroTitle: 'Les personnes grandissent. Les entreprises vont plus loin.',
  heroLead: '30Grow réunit recrutement, profils de travail et gestion des personnes pour que RH, direction et managers décident avec plus de contexte.',
  heroBody: 'La même personne passe du poste à l\'équipe : pipeline, T1–T9, Motivateurs, synthèses, 1:1, plans de développement, performance, LMS, climat et opérations RH légères. Jamais de diagnostic clinique.',
  pricingSnapshotTitle: 'Essai gratuit de 30 jours',
  pricingSnapshotBody: 'Les 20 premières entreprises bénéficient de 90 jours. Ensuite, à partir de {monthlyPrice}/mois jusqu’à {firstTierMax} collaborateurs.',
  pricingSnapshotCta: 'Calculer mon offre →',
  heroFoot: 'Déjà client ? Connectez-vous en tant que manager/RH ou collaborateur. Pas encore ? Essayez gratuitement pendant 30 jours. Ou découvrez ce qui est inclus :',
  navLogin: 'Managers / RH',
  navEmployee: 'Collaborateur',
  navPricing: 'Tarifs',
  navEarly: 'Essai gratuit de 30 jours',
  ctaEarly: 'Essai gratuit de 30 jours →',
  ctaLogin: 'Accès manager / RH',
  ctaEmployee: 'Je suis collaborateur',
  tocLabel: 'Sur cette page',
  journeyNav: 'Comment 30Grow relie le parcours',
  audienceLabel: 'Pour qui',
  audienceTitle: 'RH, direction et managers qui recrutent et accompagnent des personnes',
  audienceItems: [
    'Équipes sur des outils ATS (Gupy, Greenhouse et similaires) sans profil Ennéagramme / personnalité au travail lié au poste et à l\'équipe.',
    'Entreprises qui achètent des tests de profil isolés et reçoivent un PDF. Pas de synthèse, pas de 1:1, pas de suivi après l\'embauche ni d\'espace collaborateur.',
    'Dirigeants qui veulent des hypothèses de management (“tend à…”) plutôt que des étiquettes ou un “diagnostic”.',
  ],
  journeyLabel: 'Parcours connecté',
  journeyTitle: 'Quatre moments, un contexte partagé',
  journeyLead: 'Chaque étape réutilise les données et décisions de la précédente. L\'élément central est la personne, pas un rapport isolé.',
  journeyStages: [
    {
      title: 'Attirer et organiser',
      body: 'Publiez des offres, recevez des candidatures et gérez un pipeline kanban configurable.',
      detail: 'Offres publiques · pipeline · vivier de talents',
    },
    {
      title: 'Évaluer en contexte',
      body: 'Combinez T1–T9, Motivateurs, grille du poste, classement explicable et grilles d\'entretien.',
      detail: 'Profil de travail · adéquation · entretien',
    },
    {
      title: 'Décider et intégrer',
      body: 'Enregistrez la décision, préparez l\'arrivée et suivez les points à J30, J60 et J90.',
      detail: 'Offre · intégration · points de suivi',
    },
    {
      title: 'Développer et accompagner',
      body: 'Menez des 1:1, plans de développement, évaluations de performance, OKR, LMS, climat et routines RH légères.',
      detail: 'Management · formation · opérations',
    },
  ],
  problemLabel: 'Le problème',
  problemTitle: 'Trois produits. Zéro continuité.',
  problems: [
    {
      title: 'L\'ATS gère l\'entonnoir',
      body: 'CV, étapes, agenda. Idéal pour le volume. Faible pour expliquer l\'adéquation au poste et à l\'équipe en place.',
    },
    {
      title: 'Le test devient un fichier',
      body: 'Les batteries isolées ont l\'air soignées. Au moment de l\'entretien et du 1:1, le contexte a disparu.',
    },
    {
      title: 'Après l\'embauche, tout recommence',
      body: 'Intégration, LMS, OKR, climat et fidélisation sont ailleurs. La personne recrutée “renaît” dans un autre système.',
    },
  ],
  wedgeLabel: 'Notre approche',
  wedgeTitle: 'Une personne. Une histoire. De candidat à collaborateur.',
  wedgeBody: 'Dans 30Grow, la même personne porte l\'Ennéagramme (personnalités au travail), les Motivateurs, le classement du poste, la synthèse, les 1:1, les plans, les OKR, le LMS, les points de suivi, le climat et les opérations RH légères. Vous n\'“intégrez pas un PDF”. Vous décidez et assurez le suivi sur un seul fil.',
  outcomesLabel: 'Ce qui change',
  outcomesTitle: 'Des résultats concrets pour nos clients',
  outcomes: [
    {
      title: 'Des décisions d\'embauche plus rapides et justifiables',
      body: 'Grille par poste, classement d\'adéquation de profil explicable et synthèse d\'entretien avec à faire / à éviter. Prêt pour le jury.',
    },
    {
      title: 'Des managers prêts pour l\'échange',
      body: 'Hypothèses de management + historique des 1:1 + préparation du collaborateur. Moins de réunions génériques, des prochaines étapes plus claires.',
    },
    {
      title: 'Moins de “disparus après l\'embauche”',
      body: 'Espace collaborateur, arrivée de J1 à J90, LMS avec progression, OKR assignés et plans de développement. Avec des alertes de fidélisation actionnables.',
    },
    {
      title: 'Un outil de moins dans la stack',
      body: 'Entonnoir + profil + gestion légère des personnes + LMS/opérations RH légers. Complète votre ATS ; pas de remplacement forcé de la paie dès le premier jour.',
    },
  ],
  pillarsLabel: 'Ce que vous obtenez',
  pillarsTitle: 'Ce qui est déjà dans le produit',
  pillarsLead: 'Des fonctionnalités disponibles dès aujourd\'hui, organisées autour du travail réel des RH et de la direction.',
  pillars: [
  {
    "id": "recruit",
    "title": "Recruter avec adéquation",
    "items": [
      "Postes et pipeline kanban jusqu'à l'embauche ou l'archivage",
      "Référentiel de profils de travail réutilisable : définissez les styles de travail attendus et réutilisez-les dans de nouveaux postes",
      "Grille de profil par poste + classement d'adéquation explicable",
      "Grille d'entretien, notes enrichies, vivier de talents",
      "Analyse des départs : ce qu'il faut corriger dans le recrutement à partir des vraies raisons de départ",
      "Offres publiques et page carrières de l’entreprise avec logo et présentation",
      "Rapport de présélection client (avis + PDF)",
      "Suivi simple des offres dans l'entonnoir",
      "Indicateurs d'efficacité : délai de recrutement, fidélisation, adéquation des recrutés vs vivier"
    ]
  },
  {
    "id": "profile",
    "title": "Ennéagramme et Motivateurs qui mènent à l'action",
    "items": [
      "Test de profil inspiré de l'Ennéagramme : personnalités au travail (pas un diagnostic clinique)",
      "Motivateurs : ce qui donne de l'énergie et ce qui en prend au quotidien",
      "HR Score : signaux comportementaux consolidés (0-100) avec prévisions de turnover et écarts de PDI",
      "Radar de turnover : suivi multi-signaux du risque de départ avec actions suggérées",
      "Synthèse de décision + fiche PDF d'une page pour les entretiens",
      "Compatibilité et composition d'équipe (synergie / tension)",
      "Vue d'ensemble avec carte d'équipe et file d'attention",
      "Analyses : tendances dans le temps, comparaisons entre services, alertes d'anomalies"
    ]
  },
  {
    "id": "team",
    "title": "Management, performance et climat",
    "items": [
      "Équipe unifiée : candidats et collaborateurs",
      "1:1 avec hypothèses et prochaines étapes",
      "OKR légers (entreprise / équipe / personne) avec activités assignées aux collaborateurs",
      "Évaluations de performance : objectifs, résultats, 180°/360° en option et calibrage",
      "Plans de succession : postes clés, successeurs et niveau de préparation",
      "Canal d'alerte / prise de parole avec tri par les RH",
      "Matrice 9Box (performance × potentiel) avec un langage nuancé",
      "Feedback continu entre pairs et fil d'entreprise avec remerciements",
      "Enquêtes de climat anonymes, pulse de groupe et synthèse hebdomadaire pour les managers"
    ]
  },
  {
    "id": "journey",
    "title": "Après l'embauche et formation",
    "items": [
      "Espace collaborateur avec connexion par mot de passe : tâches, arrivée, plans, OKR et enquêtes",
      "Chronologie “Mon arrivée” : kit, fiche d'accès, appels et points J30/J60/J90",
      "LMS avec cours, lecteur, progression, quiz et certificat",
      "Bibliothèque de ressources pédagogiques liées aux plans de développement",
      "Plans de développement avec progression, cycle et responsable",
      "Catalogue des avantages de l'entreprise",
      "Alertes de fidélisation avec plan et revue",
      "Parcours continu sur la fiche de la personne"
    ]
  },
  {
    "id": "dp",
    "title": "Opérations RH légères avec la même connexion",
    "items": [
      "Profil collaborateur : adresse, identifiant fiscal et contact d'urgence",
      "Liste de documents avec dépôt par le collaborateur",
      "Demandes de congés / absences avec solde et pièces jointes",
      "Pointage web (arrivée / départ) dans l'espace collaborateur",
      "Rémunération interne et part variable (proposer / approuver) : ni paie ni bulletins de salaire",
      "Ne remplace pas une paie complète / les déclarations fiscales : opérations légères dans le même espace"
    ]
  },
  {
    "id": "organizacao",
    "title": "Organisation et accompagnement des managers",
    "items": [
      "Organigramme avec la hiérarchie des managers et des collaborateurs",
      "Répertoire des équipes et services avec une structure hiérarchique",
      "Assistant IA pour répondre aux questions sur l’utilisation de 30Grow",
      "Guide pour configurer et utiliser les modules",
      "Modules et permissions adaptés à l’accès de chaque personne",
      "Authentification à deux facteurs pour protéger l’accès des managers"
    ]
  }
],
  employeeApp: {
    label: '30Grow sur mobile',
    eyebrow: 'Application collaborateur · iOS et Android',
    title: 'La journée de travail tient aussi dans votre poche.',
    body: 'L\'application 30Grow offre aux collaborateurs une expérience native, ciblée et sécurisée. Ce n\'est pas un tableau de bord RH réduit : c\'est un parcours dédié pour consulter les priorités et agir en quelques gestes.',
    status: 'Lancement en octobre 2026 · iOS et Android',
    features: [
      'Aujourd\'hui, notifications et parcours d\'intégration',
      'Enquêtes, plans de développement, OKR et évaluations reçues',
      'Feedback et LMS avec vidéo, PDF, quiz et certificat',
      'Connexion sécurisée avec 2FA et changement d\'entreprise',
    ],
    note: 'L\'application arrive dans les stores en octobre 2026. D\'ici là, le portail web collaborateur est déjà disponible avec les mêmes parcours.',
    mockup: {
      greeting: 'Bonjour, Marina',
      context: 'Votre journée dans 30Grow',
      priority: 'Priorité du jour',
      task: 'Mettre à jour la progression du plan de développement',
      progress: '2 actions sur 4 terminées',
      next: 'Prochaines étapes',
      items: [
        'Répondre à l\'enquête pulse',
        'Poursuivre le cours de leadership',
      ],
      nav: [
        'Aujourd\'hui',
        'Parcours',
        'Apprendre',
      ],
    },
  },
  hrReports: {
    label: 'Rapports pour la gestion RH',
    title: 'Des données éparses à l\'ordre du jour de la réunion RH.',
    body: 'Les rapports de recrutement, de progression et de fidélisation aident les RH à comparer les périodes, à analyser les causes et à choisir la prochaine priorité.',
    groups: [
      {
        title: 'Mieux recruter',
        body: 'Délai de recrutement, conversion de l\'entonnoir, adéquation des recrutés et respect de la grille.',
        icon: 'vacancies',
      },
      {
        title: 'Suivre la progression',
        body: 'Productivité, fidélisation, HR Score et embauches par rapport aux départs.',
        icon: 'chart',
      },
      {
        title: 'Anticiper les points d\'attention',
        body: 'Climat, risque de turnover, comparaisons entre services et alertes agrégées.',
        icon: 'climate',
      },
    ],
    delivery: 'Filtres par période, comparaison entre services, exports et envoi hebdomadaire ou mensuel avec PDF en option.',
    guardrail: 'Les indicateurs montrent où creuser. Ils ne prennent aucune décision automatisée sur les personnes.',
    preview: {
      label: 'Lecture de direction',
      title: 'Synthèse des personnes',
      period: '12 derniers mois',
      metrics: [
        {
          label: 'Délai de recrutement',
          value: '34 jours',
          trend: '−8%',
        },
        {
          label: 'Fidélisation à 12 mois',
          value: '82%',
          trend: '+5%',
        },
        {
          label: 'Adéquation des recrutés',
          value: '7.8/10',
          trend: '+0.6',
        },
      ],
      trendTitle: 'Embauches et départs',
      alertTitle: 'Ordre du jour suggéré',
      alert: 'Examiner l\'étape où l\'attente est la plus longue',
    },
  },
  compareLabel: 'Positionnement',
  compareTitle: 'Où 30Grow fait la différence (et où il ne se positionne pas)',
  compareLead: 'Sans dénigrer personne : aider l\'acheteur à choisir la bonne catégorie.',
  compareRows: [
    {
      them: 'ATS classique (ex. Gupy, Greenhouse)',
      gap: 'Solide sur le volume, les étapes, les pages carrières.',
      us: '30Grow ajoute Ennéagramme + décision + suivi après l\'embauche sur le même fil de la personne.',
    },
    {
      them: 'Test isolé / PDF de profil',
      gap: 'Un rapport qui n\'entre jamais dans le flux RH.',
      us: 'Le test de profil devient synthèse, classement du poste et trame de 1:1.',
    },
    {
      them: 'Engagement / climat uniquement',
      gap: 'Mesure le ressenti après coup : déconnecté du recrutement.',
      us: 'Climat, pulse, OKR et LMS suivent le même profil que celui du recrutement.',
    },
    {
      them: 'SIRH complet / paie',
      gap: 'Embauches administratives, bulletins de salaire, déclarations fiscales.',
      us: 'Ne les remplace pas : LMS et opérations RH légers plus espace collaborateur sur le produit de profil.',
    },
  ],
  builderLabel: 'Origine',
  builderTitle: 'Pourquoi 3035Tech a créé 30Grow',
  builderParagraphs: [
    '30Grow est né chez 3035Tech : une société d\'ingénierie logicielle qui recrute et constitue des équipes en permanence. La douleur était la nôtre : des décisions à l\'instinct, des PDF que personne ne rouvre et une histoire de la personne à reprendre de zéro après l\'embauche.',
    'Nous utilisons réellement le produit. Nous recrutons avec, formons les personnes via 3035TEACH et gérons l\'équipe dans le même flux. Pas une présentation : un outil qui a fait ses preuves dans nos propres RH avant de devenir une offre.',
    '3035Tech s\'en porte garant : une ingénierie sérieuse. Le héros de la page, et du quotidien, reste 30Grow.',
  ],
  howLabel: 'Comment démarrer',
  howTitle: 'Trois étapes vers la valeur',
  steps: [
    {
      n: '01',
      title: 'Lancer l\'essai',
      body: 'Créez votre compte ou échangez avec 3035Tech, obtenez l\'accès manager et configurez l\'entreprise.',
    },
    {
      n: '02',
      title: 'Lancer un poste ou l\'équipe',
      body: 'Invitez des personnes par lien (sans compte candidat). Consultez classement et synthèse en moins d\'une semaine.',
    },
    {
      n: '03',
      title: 'Boucler la boucle',
      body: 'Recrutez avec contexte et suivez arrivée → espace collaborateur → 1:1 / OKR / LMS. Sans changer d\'outil.',
    },
  ],
  trustLabel: 'Confiance',
  trustTitle: 'Un langage sérieux : des limites claires',
  trustItems: [
    'Des hypothèses de management (“tend à”), jamais un diagnostic clinique.',
    'Ne remplace pas les entretiens techniques ni les évaluations de santé.',
    'L\'Ennéagramme au travail : profil de style de travail, pas un rapport clinique.',
    'Les candidats ne créent pas de compte : ils utilisent le lien envoyé par les RH. Les collaborateurs peuvent avoir une connexion par mot de passe.',
    'Les données de chaque entreprise restent isolées.',
    'Accompagnement initial avec 3035Tech et sans engagement obligatoire.',
  ],
  faqLabel: 'Questions d\'achat',
  faqTitle: 'FAQ commerciale',
  faqs: [
    {
      q: 'Est-ce vraiment gratuit ?',
      a: 'Oui. Chaque entreprise démarre avec 30 jours gratuits. Les 20 premières bénéficient de 90 jours ; les partenaires de conception peuvent négocier jusqu\'à 6 mois. Ensuite, les offres démarrent à {monthlyPrice}/mois jusqu’à {firstTierMax} collaborateurs, avec 20 % de remise en facturation annuelle.',
    },
    {
      q: 'Dois-je abandonner mon ATS ?',
      a: 'Non. 30Grow inclut entonnoir et profil, mais sa valeur principale est la décision et le suivi après l\'embauche. De nombreuses équipes commencent en parallèle de leur ATS actuel.',
    },
    {
      q: 'Est-ce encore un test de personnalité ?',
      a: 'Non. Un test de profil Ennéagramme au travail + Motivateurs liés au poste, à l\'équipe, à l\'entretien et au 1:1. Pas un diagnostic clinique.',
    },
    {
      q: 'Les collaborateurs l\'utilisent-ils aussi ?',
      a: 'Oui. Le portail /employee couvre l\'arrivée, les enquêtes, les plans, les OKR, le LMS, les opérations RH légères et le pointage web. L\'application native, lancée en octobre 2026, apporte Aujourd\'hui, notifications, intégration, enquêtes, plans, OKR, évaluations, feedback et LMS sur iOS et Android. Il existe aussi un lien léger /e par token sans mot de passe.',
    },
    {
      q: 'En combien de temps voit-on la valeur ?',
      a: 'Dès le premier poste ou le premier groupe de l\'équipe : classement, synthèse et un 1:1 font déjà mieux qu\'un PDF.',
    },
    {
      q: 'Comment obtenir un accès ?',
      a: 'Cliquez sur “Essai gratuit de 30 jours” ou écrivez à contact@3035tech.com en indiquant votre entreprise et votre rôle (RH/manager).',
    },
  ],
  earlyLabel: 'Offre',
  earlyTitle: '90 jours gratuits pour les 20 premières entreprises',
  earlyBody: 'Chaque entreprise démarre avec 30 jours gratuits. Les 20 premières bénéficient de 90 jours ; les partenaires de conception peuvent négocier jusqu\'à 6 mois. Ensuite, continuez à partir de {monthlyPrice}/mois jusqu’à {firstTierMax} collaborateurs.',
  earlyProof: [
    'Sans carte · sans engagement obligatoire',
    'Accompagnement avec 3035Tech',
    '5 collaborateurs minimum',
  ],
  earlyContact: 'Ou écrivez à',
  earlyMailSubject: '30Grow : accès anticipé gratuit',
  earlyMailBody: 'Bonjour ! Je souhaite un accès anticipé gratuit à 30Grow.\n\nEntreprise :\nNom :\nRôle (RH / manager / direction) :\nTaille approx. de l\'équipe :\nPrincipale difficulté aujourd\'hui (ATS / test PDF / après l\'embauche) :\n',
  closeTitle: 'Prêt à obtenir le “oui” en interne ?',
  closeBody: 'Montrez à votre équipe un flux du candidat à l\'espace collaborateur. Sans tableur supplémentaire. Commencez avec 30 jours gratuits.',
  footerBrand: '30Grow',
  footerCred: 'Conçu par 3035Tech : ingénierie logicielle depuis ~19 ans, avec des clients au Brésil, en Irlande, aux États-Unis et en Allemagne.',
  footerPricing: 'Offres et tarifs',
  footerPrivacy: 'Confidentialité',
  footerTerms: 'Conditions',
  footerLegal: 'Logiciel RH avec Ennéagramme, Motivateurs et recrutement. Des hypothèses de management, pas un diagnostic.',
  skipToContent: 'Aller au contenu',
};
