/**
 * Content-Security-Policy — opt-in via ENABLE_CSP=true (runtime, middleware).
 * Report-only continua disponível via CSP_REPORT_ONLY (sem enforcement).
 */

/**
 * Política padrão alinhada ao stack Next 16 + logos S3 + player LMS (YouTube/Vimeo)
 * + Turnstile + Cloudflare Web Analytics (beacon injetado na borda quando Insights está ligado).
 */
export function buildDefaultContentSecurityPolicy(nonce) {
  let sentryOrigin = '';
  try {
    const dsn = new URL(process.env.NEXT_PUBLIC_SENTRY_DSN || process.env.SENTRY_DSN || '');
    if (dsn.protocol === 'https:') sentryOrigin = dsn.origin;
  } catch {
    // Sentry is optional; only its HTTPS origin belongs in the policy.
  }

  // Production scripts use a fresh nonce; only development needs eval for HMR.
  const scriptSources = [
    "'self'",
    nonce && `'nonce-${nonce}'`,
    process.env.NODE_ENV === 'development' && "'unsafe-eval'",
    'https://challenges.cloudflare.com',
    'https://static.cloudflareinsights.com',
    'https://www.youtube.com',
    'https://s.ytimg.com',
    'https://player.vimeo.com',
    'https://js.sentry-cdn.com',
  ].filter(Boolean).join(' ');
  const connectSources = [
    "'self'",
    'https://challenges.cloudflare.com',
    'https://cloudflareinsights.com',
    'https://*.cloudflareinsights.com',
    sentryOrigin,
  ].filter(Boolean).join(' ');

  return [
    "default-src 'self'",
    `script-src ${scriptSources}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob: https:",
    "media-src 'self' blob: https:",
    "worker-src 'self' blob:",
    "font-src 'self' data:",
    `connect-src ${connectSources}`,
    "frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com https://player.vimeo.com https://challenges.cloudflare.com https://www.openstreetmap.org",
    "frame-ancestors 'self'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
  ].join('; ');
}

export function resolveContentSecurityPolicy(nonce) {
  const custom = String(process.env.CSP_POLICY || '').trim();
  if (custom) return custom;
  return buildDefaultContentSecurityPolicy(nonce);
}

/**
 * @param {import('next/server').NextResponse} response
 * @param {string} nonce - Fresh nonce generated by the proxy for this request.
 */
export function applyContentSecurityPolicyHeaders(response, nonce) {
  const enforce = process.env.ENABLE_CSP === 'true';
  const reportOnly = String(process.env.CSP_REPORT_ONLY || '').trim();

  if (enforce) {
    response.headers.set('Content-Security-Policy', resolveContentSecurityPolicy(nonce));
    return response;
  }

  if (reportOnly) {
    response.headers.set(
      'Content-Security-Policy-Report-Only',
      reportOnly === 'true' ? resolveContentSecurityPolicy(nonce) : reportOnly
    );
  }

  return response;
}
