const {test, expect} = require('@playwright/test');
test('employee priorities, PDI filters, DP keyboard navigation and completed courses', async ({page}) => {
  await page.goto('/employee-preview');
  await expect(page.getByRole('heading', {name:'Olá, Pessoa de teste'})).toBeVisible({timeout:20000});
  await expect(page.getByRole('link',{name:'3 Pesquisas abertas'})).toBeVisible();
  await expect(page.locator('#tasks').getByText('Atrasado', {exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Recolher seções',exact:true}).click();
  await expect(page.locator('#tasks').getByRole('button')).toHaveAttribute('aria-expanded','false');
  await page.getByRole('link',{name:'1 Pendências',exact:true}).click();
  await expect(page.locator('#tasks').getByRole('button')).toHaveAttribute('aria-expanded','true');
  await page.getByRole('button',{name:'pdi',exact:true}).click();
  await expect(page.getByRole('tab',{name:'Pendentes 2'})).toHaveAttribute('aria-selected','true');
  await expect(page.getByText('Concluir integração', {exact:true})).toBeHidden();
  await expect(page.locator('#pdi-results li').first()).toContainText('Consolidar rituais');
  await page.getByRole('tab',{name:'Concluídos 1'}).click();
  await expect(page.getByText('Concluir integração', {exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Reabrir'})).toBeVisible();
  await page.getByRole('button',{name:'dp',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Checklist documental'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Informações cadastrais'})).toBeHidden();
  await page.getByRole('tab',{name:'Checklist documental 2'}).focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('heading',{name:'Férias e afastamentos'})).toBeVisible();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('button',{name:'Editar ficha'})).toBeVisible();
  await page.getByRole('button',{name:'lms',exact:true}).click();
  await expect(page.getByRole('button',{name:'Ver aulas'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Continuar',exact:true})).toBeHidden();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'dp',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Checklist documental'})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button',{name:'pdi',exact:true}).click();
  await expect(page.getByRole('button',{name:'Marcar como feito'}).first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('profile uses account/security pattern and preserves drafts across tabs', async ({page}) => {
  const writes = [];
  page.on('request', request => { if (request.url().includes('/api/') && request.method() !== 'GET') writes.push(request.url()); });
  await page.goto('/employee-preview');
  await page.getByRole('button',{name:'profile',exact:true}).click();
  await expect(page.getByRole('tab',{name:'Minha conta',exact:true})).toBeVisible({timeout:20000});
  await page.getByLabel('Nome completo',{exact:true}).fill('Rascunho preservado');
  await page.getByRole('tab',{name:'Segurança',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Autenticação em duas etapas (2FA)'})).toBeVisible();
  await expect(page.getByLabel('Senha atual',{exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Minha conta',exact:true}).click();
  await expect(page.getByLabel('Nome completo',{exact:true})).toHaveValue('Rascunho preservado');
  await expect(page.getByLabel('E-mail',{exact:true})).toBeDisabled();
  await expect(page.getByRole('tab',{name:'Módulos',exact:true})).toHaveCount(0);
  await expect(page.getByRole('tab',{name:'Assinatura',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Menu do perfil',exact:true}).click();
  await expect(page.getByRole('menuitem',{name:'Meu perfil',exact:true})).toBeVisible();
  await expect(page.getByRole('menuitem',{name:'Sair',exact:true})).toBeVisible();
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('tab',{name:'Segurança',exact:true}).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const notifications = await page.getByRole('button',{name:'Notificações',exact:true}).boundingBox();
  const profile = await page.getByRole('button',{name:'Menu do perfil',exact:true}).boundingBox();
  expect(Math.abs(notifications.y - profile.y)).toBeLessThanOrEqual(2);
  expect(writes).toEqual([]);
  await page.screenshot({path:test.info().outputPath('employee-profile-mobile.png'),fullPage:true});
});
