import { test, expect } from '@playwright/test';
import { HR } from './fixtures.js';

async function openMenuItem(page, trigger, name) {
  const item=page.getByRole('menuitem',{name,exact:true});
  await expect(async()=>{
    if (!(await item.isVisible())) await trigger.click();
    await item.click({timeout:1000});
  }).toPass({timeout:15000});
}

test('OKR: area → objective → measured KR, history, employee check-in and closed-cycle enforcement', async ({page,browser,baseURL}) => {
  test.setTimeout(120000);
  page.setDefaultTimeout(15000);
  expect(['localhost','127.0.0.1']).toContain(new URL(baseURL).hostname);
  expect((await page.request.post('/api/auth/login',{data:HR})).ok()).toBeTruthy();
  const employees=await (await page.request.get('/api/admin/employees/search?q=colaborador%40todos-os-dados.demo')).json();
  const employee=employees.items[0];
  expect(employee).toBeTruthy();
  const stamp=Date.now();
  const response=await page.request.post('/api/admin/okr/cycles',{data:{title:`OKR E2E ${stamp}`,startsOn:'2026-01-01',endsOn:'2026-12-31'}});
  expect(response.ok()).toBeTruthy();
  const {cycle}=await response.json();
  let employeeContext;
  let mobileTokens;
  try {
    const areaResponse=await page.request.post('/api/admin/okr/areas',{data:{cycleId:cycle.id,title:`Comercial ${stamp}`}});
    expect(areaResponse.ok()).toBeTruthy();
    await page.goto('/dashboard?tab=okr');
    await page.getByRole('combobox',{name:'Ciclo OKR ativo'}).click();
    await page.getByRole('option',{name:cycle.title,exact:true}).click();
    const area=page.getByRole('region',{name:`Área: Comercial ${stamp}`,exact:true});
    await area.getByRole('button',{name:'Novo objetivo',exact:true}).click();
    let dialog=page.getByRole('dialog');
    await dialog.getByLabel('Título',{exact:true}).fill('Acelerar vendas');
    await page.route('**/api/admin/okr/hierarchy', route=>route.request().method()==='POST' ? route.fulfill({status:503,json:{error:'Falha simulada. Tente novamente.'}}) : route.continue(),{times:1});
    await dialog.getByRole('button',{name:'Salvar',exact:true}).click();
    await expect(dialog.getByRole('alert')).toContainText('Falha simulada');
    await expect(dialog.getByLabel('Título',{exact:true})).toHaveValue('Acelerar vendas');
    await dialog.getByRole('button',{name:'Salvar',exact:true}).click();
    const objective=area.getByRole('article',{name:'Objetivo: Acelerar vendas',exact:true});
    await expect(objective).toBeVisible();
    await openMenuItem(page,objective.getByRole('button',{name:'Mais ações: Acelerar vendas',exact:true}),'Editar objetivo');
    await page.getByRole('dialog').getByLabel('Descrição',{exact:true}).fill('Objetivo mensurável da área comercial.');
    await page.getByRole('dialog').getByRole('combobox',{name:'Responsável',exact:true}).fill(employee.label);
    await page.getByRole('dialog').getByRole('option').filter({hasText:employee.label}).click();
    await page.getByRole('dialog').getByRole('button',{name:'Salvar',exact:true}).click();
    await expect(objective).toContainText(employee.label);
    await openMenuItem(page,objective.getByRole('button',{name:'Mais ações: Acelerar vendas',exact:true}),'Editar objetivo');
    await expect(page.getByRole('dialog').getByRole('combobox',{name:'Responsável',exact:true})).toHaveValue(employee.label);
    await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();
    await expect(page.getByRole('menuitem',{name:'Excluir objetivo',exact:true})).toBeHidden();
    await objective.getByRole('button',{name:'Novo resultado-chave',exact:true}).click();
    dialog=page.getByRole('dialog');
    await dialog.getByLabel('Título',{exact:true}).fill('Reduzir prazo de venda');
    await dialog.getByLabel('Unidade',{exact:true}).fill('dias');
    await dialog.getByLabel('Valor inicial',{exact:true}).fill('10');
    await dialog.getByRole('spinbutton',{name:'Meta',exact:true}).fill('5');
    await dialog.getByRole('combobox',{name:'Responsável',exact:true}).fill(employee.label);
    await dialog.getByRole('option').filter({hasText:employee.label}).click();
    await dialog.getByRole('spinbutton',{name:'Meta',exact:true}).fill('10');
    await dialog.getByRole('button',{name:'Salvar',exact:true}).click();
    await expect(dialog.getByRole('alert')).toContainText('A meta deve ser diferente');
    await expect(dialog.getByRole('spinbutton',{name:'Meta',exact:true})).toHaveAttribute('aria-invalid','true');
    await dialog.getByRole('spinbutton',{name:'Meta',exact:true}).fill('5');
    await dialog.getByRole('button',{name:'Salvar',exact:true}).click();
    const kr=objective.getByRole('listitem',{name:'Resultado-chave: Reduzir prazo de venda',exact:true});
    await kr.getByRole('button',{name:'Ver detalhes',exact:true}).click();
    await expect(kr.getByRole('definition').nth(2)).toContainText('10');
    await kr.getByRole('button',{name:'Registrar check-in',exact:true}).click();
    await page.getByRole('dialog').getByLabel('Valor atual (dias)',{exact:true}).fill('7.5');
    await page.getByRole('dialog').getByLabel('Comentário',{exact:true}).fill('Melhoria comprovada');
    await page.getByRole('dialog').getByRole('button',{name:'Salvar',exact:true}).click();
    await expect(kr.getByRole('definition').nth(2)).toContainText('7,5');
    await expect(kr).toContainText('50%');
    await kr.getByRole('button',{name:'Ver histórico de medições',exact:true}).click();
    await expect(kr.getByRole('list',{name:'Histórico de medições'})).toContainText('Melhoria comprovada');
    await expect(page.getByRole('status').filter({hasText:'Alteração salva.'})).toHaveCount(1);
    await page.screenshot({path:'/private/tmp/okr-hierarchy-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await expect(page.locator('.db-sidebar')).not.toBeInViewport();
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
    await kr.scrollIntoViewIfNeeded();
    await page.screenshot({path:'/private/tmp/okr-hierarchy-mobile.png'});
    const pack=await (await page.request.get(`/api/admin/okr/hierarchy?cycleId=${cycle.id}`)).json();
    expect(pack.cycle.id).toBe(cycle.id);
    const saved=pack.cycle.areas[0].objectives[0];
    const keyResultId=saved.keyResults[0].id;
    // An old endpoint must not bypass the numeric-history contract.
    expect((await page.request.patch(`/api/admin/okr/key-results/${keyResultId}`,{data:{currentValue:100}})).ok()).toBeFalsy();
    employeeContext=await browser.newContext({baseURL});
    const employeePage=await employeeContext.newPage();
    const login=await employeePage.request.post('/api/auth/employee/login',{data:{email:'colaborador@todos-os-dados.demo',password:HR.password}});
    expect(login.ok()).toBeTruthy();
    await employeePage.goto('/employee#okr');
    const employeeKr=employeePage.locator('#okr li').filter({hasText:'Reduzir prazo de venda'}).filter({hasText:`Comercial ${stamp}`});
    await expect(employeeKr).toContainText('Acelerar vendas');
    await employeeKr.getByRole('button',{name:'Check-in',exact:true}).click();
    await employeePage.getByRole('dialog').getByLabel('Valor atual (dias)',{exact:true}).fill('6');
    await employeePage.getByRole('dialog').getByRole('textbox').fill('Employee measurement');
    await employeePage.route('**/api/employee/okr/checkins',route=>route.fulfill({status:503,json:{error:'Falha simulada no check-in.'}}),{times:1});
    await employeePage.getByRole('dialog').getByRole('button',{name:/Salvar|Registrar/}).click();
    await expect(employeePage.getByRole('dialog').getByRole('alert')).toContainText('Falha simulada');
    await expect(employeePage.getByRole('dialog').getByLabel('Valor atual (dias)',{exact:true})).toHaveValue('6');
    await expect(employeePage.getByRole('dialog').getByRole('textbox')).toHaveValue('Employee measurement');
    await employeePage.getByRole('dialog').getByRole('button',{name:/Salvar|Registrar/}).click();
    await expect(employeeKr).toContainText('Atual: 6 dias');
    await openMenuItem(page,kr.getByRole('button',{name:'Mais ações: Reduzir prazo de venda',exact:true}),'Editar resultado-chave');
    await page.getByRole('dialog').getByRole('spinbutton',{name:'Meta',exact:true}).fill('0');
    await page.getByRole('dialog').getByRole('button',{name:'Salvar',exact:true}).click();
    await expect(kr.getByRole('definition').nth(2)).toContainText('6');
    await expect(kr).toContainText('40%');
    const mobileLogin=await page.request.post('/api/mobile/v1/auth/login',{data:{email:'colaborador@todos-os-dados.demo',password:HR.password}});
    expect(mobileLogin.ok()).toBeTruthy();
    mobileTokens=(await mobileLogin.json()).session.tokens;
    const headers={Authorization:`Bearer ${mobileTokens.accessToken}`};
    const mobilePack=await (await page.request.get('/api/mobile/v1/employee/okrs',{headers})).json();
    expect(mobilePack.keyResults.find(k=>k.id===keyResultId).objectiveTitle).toBe('Acelerar vendas');
    expect(Array.isArray(mobilePack.activities)).toBeTruthy();
    expect((await page.request.post('/api/mobile/v1/employee/okrs',{headers,data:{keyResultId,currentValue:5.5,note:'Mobile measurement'}})).ok()).toBeTruthy();
    expect((await page.request.patch(`/api/admin/okr/cycles/${cycle.id}`,{data:{status:'closed'}})).ok()).toBeTruthy();
    expect((await employeePage.request.post('/api/employee/okr/checkins',{data:{keyResultId,currentValue:5}})).ok()).toBeFalsy();
    expect((await page.request.post('/api/admin/okr/hierarchy',{data:{action:'checkin',keyResultId,currentValue:5}})).ok()).toBeFalsy();
    expect((await page.request.post('/api/mobile/v1/employee/okrs',{headers,data:{keyResultId,currentValue:5}})).ok()).toBeFalsy();
    await page.reload();
    await page.getByRole('combobox',{name:'Ciclo OKR ativo'}).click();
    await page.getByRole('option',{name:cycle.title,exact:true}).click();
    await expect(kr.getByRole('button',{name:'Registrar check-in',exact:true})).toBeDisabled();
    await kr.getByRole('button',{name:'Ver detalhes',exact:true}).click();
    await kr.getByRole('button',{name:'Ver histórico de medições',exact:true}).click();
    await expect(kr.getByRole('list',{name:'Histórico de medições'})).toContainText('Employee measurement');
    await expect(kr.getByRole('list',{name:'Histórico de medições'})).toContainText('Mobile measurement');
  } finally {
    if(mobileTokens?.refreshToken) await page.request.post('/api/mobile/v1/session/logout',{data:{refreshToken:mobileTokens.refreshToken}});
    await employeeContext?.close();
    await page.request.patch(`/api/admin/okr/cycles/${cycle.id}`,{data:{status:'active'}});
    const removed=await page.request.delete(`/api/admin/okr/cycles/${cycle.id}`);
    expect(removed.ok()).toBeTruthy();
  }
});
